#!/bin/sh

EFM_THEME_PATH=/Library/Themes/EmojiFontManager

if [ ! -d ${EFM_THEME_PATH} ]
then
    echo "No Anemone Wrapper removing"
    exit 0
fi

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

for theme in $(find ${EFM_THEME_PATH} -maxdepth 1 -type l -name "*.font")
do
    if [ -L "${theme}" ]
    then
        rm -rf "${theme}"
    fi
done

IFS=$SAVEIFS

killall -9 com.apple.WebKit.WebContent || true
